HAMMER TIME!

diff --git a/meteor b/meteor
--- a/meteor
+++ b/meteor
@@ -5,7 +5,7 @@ BUNDLE_VERSION=0.4.41
 # OS Check. Put here because here is where we download the precompiled
 # bundles that are arch specific.
 UNAME=$(uname)
-if [ "$UNAME" != "Linux" -a "$UNAME" != "Darwin" ] ; then
+if [ "$UNAME" != "Linux" -a "$UNAME" != "Darwin" -a "$UNAME" != "FreeBSD" ] ; then
     echo "Sorry, this OS is not supported."
     exit 1
 fi
@@ -25,6 +25,13 @@ elif [ "$UNAME" = "Linux" ] ; then
         echo "Unsupported architecture: $ARCH"
         echo "Meteor only supports i686 and x86_64 for now."
         exit 1
+    fi
+elif [ "$UNAME" = "FreeBSD" ] ; then
+    ARCH="$(uname -m)"
+    if [ "$ARCH" != "i686" -a "$ARCH" != "amd64" ] ; then
+       echo "Unsupported architecture: $ARCH"
+       echo "Meteor only supports i686 and amd64 for now."
+       exit 1
     fi
 fi
 PLATFORM="${UNAME}_${ARCH}"
@@ -50,67 +57,51 @@ cd "$ORIG_DIR"
 
 
 
-function install_dev_bundle {
-    set -e
-    trap "echo Failed to install dependency kit." EXIT
+#function install_dev_bundle {
+#    set -e
+#    trap "echo Failed to install dependency kit." EXIT
+#
+#    TARBALL="dev_bundle_${PLATFORM}_${BUNDLE_VERSION}.tar.gz"
+#    BUNDLE_TMPDIR="$SCRIPT_DIR/dev_bundle.xxx"
+#
+#    rm -rf "$BUNDLE_TMPDIR"
+#    mkdir "$BUNDLE_TMPDIR"
+#
+#    # duplicated in scripts/windows/download-dev-bundle.ps1:
+#    DEV_BUNDLE_URL_ROOT="https://d3sqy0vbqsdhku.cloudfront.net/"
+#    # If you set $USE_TEST_DEV_BUNDLE_SERVER then we will download
+#    # dev bundles copied by copy-dev-bundle-from-jenkins.sh without --prod.
+#    # It still only does this if the version number has changed
+#    # (setting it won't cause it to automatically delete a prod dev bundle).
+#    if [ -n "$USE_TEST_DEV_BUNDLE_SERVER" ] ; then
+#        DEV_BUNDLE_URL_ROOT="https://s3.amazonaws.com/com.meteor.static/test/"
+#    fi
+#
+#    if [ -f "$SCRIPT_DIR/$TARBALL" ] ; then
+#        echo "Skipping download and installing kit from $SCRIPT_DIR/$TARBALL" >&2
+#        tar -xzf "$SCRIPT_DIR/$TARBALL" -C "$BUNDLE_TMPDIR"
+#    elif [ -n "$SAVE_DEV_BUNDLE_TARBALL" ] ; then
+#        # URL duplicated in tools/server/target.sh.in
+#        curl -# "$DEV_BUNDLE_URL_ROOT$TARBALL" >"$SCRIPT_DIR/$TARBALL"
+#        tar -xzf "$SCRIPT_DIR/$TARBALL" -C "$BUNDLE_TMPDIR"
+#    else
+#        curl -# "$DEV_BUNDLE_URL_ROOT$TARBALL" | tar -xzf - -C "$BUNDLE_TMPDIR"
+#    fi
+#
+#    test -x "${BUNDLE_TMPDIR}/bin/node" # bomb out if it didn't work, eg no net
+#
+#    # Delete old dev bundle and rename the new one on top of it.
+#    rm -rf "$SCRIPT_DIR/dev_bundle"
+#    mv "$BUNDLE_TMPDIR" "$SCRIPT_DIR/dev_bundle"
+#
+#    echo "Installed dependency kit v${BUNDLE_VERSION} in dev_bundle." >&2
+#    echo >&2
+#
+#    trap - EXIT
+#    set +e
+#}
 
-    TARBALL="dev_bundle_${PLATFORM}_${BUNDLE_VERSION}.tar.gz"
-    BUNDLE_TMPDIR="$SCRIPT_DIR/dev_bundle.xxx"
 
-    rm -rf "$BUNDLE_TMPDIR"
-    mkdir "$BUNDLE_TMPDIR"
-
-    # duplicated in scripts/windows/download-dev-bundle.ps1:
-    DEV_BUNDLE_URL_ROOT="https://d3sqy0vbqsdhku.cloudfront.net/"
-    # If you set $USE_TEST_DEV_BUNDLE_SERVER then we will download
-    # dev bundles copied by copy-dev-bundle-from-jenkins.sh without --prod.
-    # It still only does this if the version number has changed
-    # (setting it won't cause it to automatically delete a prod dev bundle).
-    if [ -n "$USE_TEST_DEV_BUNDLE_SERVER" ] ; then
-        DEV_BUNDLE_URL_ROOT="https://s3.amazonaws.com/com.meteor.static/test/"
-    fi
-
-    if [ -f "$SCRIPT_DIR/$TARBALL" ] ; then
-        echo "Skipping download and installing kit from $SCRIPT_DIR/$TARBALL" >&2
-        tar -xzf "$SCRIPT_DIR/$TARBALL" -C "$BUNDLE_TMPDIR"
-    elif [ -n "$SAVE_DEV_BUNDLE_TARBALL" ] ; then
-        # URL duplicated in tools/server/target.sh.in
-        curl -# "$DEV_BUNDLE_URL_ROOT$TARBALL" >"$SCRIPT_DIR/$TARBALL"
-        tar -xzf "$SCRIPT_DIR/$TARBALL" -C "$BUNDLE_TMPDIR"
-    else
-        curl -# "$DEV_BUNDLE_URL_ROOT$TARBALL" | tar -xzf - -C "$BUNDLE_TMPDIR"
-    fi
-
-    test -x "${BUNDLE_TMPDIR}/bin/node" # bomb out if it didn't work, eg no net
-
-    # Delete old dev bundle and rename the new one on top of it.
-    rm -rf "$SCRIPT_DIR/dev_bundle"
-    mv "$BUNDLE_TMPDIR" "$SCRIPT_DIR/dev_bundle"
-
-    echo "Installed dependency kit v${BUNDLE_VERSION} in dev_bundle." >&2
-    echo >&2
-
-    trap - EXIT
-    set +e
-}
-
-
-if [ -d "$SCRIPT_DIR/.git" ] || [ -f "$SCRIPT_DIR/.git" ]; then
-    # In a checkout.
-    if [ ! -d "$SCRIPT_DIR/dev_bundle" ] ; then
-        echo "It's the first time you've run Meteor from a git checkout." >&2
-        echo "I will download a kit containing all of Meteor's dependencies." >&2
-        install_dev_bundle
-    elif [ ! -f "$SCRIPT_DIR/dev_bundle/.bundle_version.txt" ] ||
-        grep -qvx "$BUNDLE_VERSION" "$SCRIPT_DIR/dev_bundle/.bundle_version.txt" ; then
-        echo "Your dependency kit is out of date. I will download the new one." >&2
-        install_dev_bundle
-    fi
-
-    export BABEL_CACHE_DIR="$SCRIPT_DIR/.babel-cache"
-fi
-
-DEV_BUNDLE="$SCRIPT_DIR/dev_bundle"
 METEOR="$SCRIPT_DIR/tools/main-transpile-wrapper.js"
 
 
@@ -132,4 +123,4 @@ fi
 # the script take precedence over $NODE_PATH; it used to be that users would
 # screw up their meteor installs by have a ~/node_modules
 
-exec "$DEV_BUNDLE/bin/node" "$METEOR" "$@"
+exec "node" "$METEOR" "$@"
